name: boom-paper
title: A real-time, multi-survey, optical alert system broker operating
  at scale
environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  boom:
    kind: docker
    path: Dockerfile-boom
    image: boom/boom-benchmarking
    description: BOOM benchmarking image
    user: root
    deps:
      - boom/src
      - boom/Cargo.lock
      - boom/Cargo.toml
      - config/boom/config.yaml
      - boom/data/models
  analyze-logs:
    path: config/envs/analyze-logs.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"
pipeline:
  stages:
    # TODO: Add manual step stage for exporting workflow diagram
    # This stage is here because Kowalski can't be built by default with a
    # simple docker build; it is built with a Python script
    make-kowalski-version-file:
      kind: shell-command
      command: echo benchmarking > kowalski/version.txt
      environment: _system
      always_run: true
    make-kowalski-mongo-key-file:
      kind: shell-command
      command: echo thisisarandomkeyfortesting > kowalski/mongo_key.yaml
      environment: _system
      always_run: true
    benchmark-boom:
      kind: shell-script
      script_path: scripts/benchmark-boom.sh
      environment: _system
      inputs:
        - boom/src
        - boom/Cargo.lock
        - boom/Cargo.toml
        - config/boom/config.yaml
        - config/boom/compose.yaml
        - config/boom/config-consumer.yaml
        - .calkit/env-locks/boom.json
      outputs:
        - logs/boom/producer.log
        - logs/boom/consumer.log
        - logs/boom/scheduler.log
    benchmark-kowalski:
      kind: shell-script
      script_path: scripts/benchmark-kowalski.sh
      environment: _system
      inputs:
        - config/kowalski/config.yaml
        - config/kowalski/compose.yaml
        - config/kowalski/supervisord.conf
        - kowalski/ingester.Dockerfile
        - kowalski/kowalski
        - kowalski/Makefile
      outputs:
        - logs/kowalski
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: analyze-logs
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage: git
      inputs:
        - from_stage_outputs: benchmark-boom
        - from_stage_outputs: benchmark-kowalski
      outputs:
        - path: paper/results.tex
          storage: git
    build-paper:
      kind: latex
      environment: tex
      target_path: paper/main.tex
      force: true
      inputs:
        - paper/references.bib
        - paper/figures/workflow.pdf
        - paper/aasjournal.bst
        - paper/aastex631.cls
        - paper/results.tex
figures:
  - path: paper/figures/workflow.pdf
    title: BOOM workflow
publications:
  - path: paper/main.pdf
    title: A real-time, multi-survey, optical alert system broker operating
      at scale
    description:
    kind: journal-article
    stage: build-paper
    overleaf:
      project_id: 67eb247c542af4e06002e7e8
      wdir: paper
      sync_paths:
        - main.tex
        - references.bib
        - aasjournal.bst
        - aastex631.cls
      # Keep these out of Git in this project so we don't bloat the repo, but
      # can still version them with DVC
      dvc_sync_paths:
        - figures/workflow.key
        - figures/workflow.pdf
      push_paths:
        - results.tex
      last_sync_commit: d18d1cb8e2dc392f5fde17a046406fbfcc8552e9
notebooks:
  - path: notebooks/analyze-logs.ipynb
    title: Analyzing the logs
    description: Analyze the logs from the BOOM and Kowalski benchmarks.
references:
  - path: paper/references.bib
showcase:
  - publication: paper/main.pdf
