name: boom-paper
title: A real-time, multi-survey, optical alert system broker 
  operating at scale
description: >
  This project contains all of the files necessary to reproduce the results
  and compile the paper.

authors:
  - first_name: Theophile
    last_name: Jegou du Laz
    affiliation: >
      Division of Physics, Mathematics, and Astronomy,
      California Institute of Technology, Pasadena, CA 91125, USA
    orcid: 0009-0003-6181-4526
  - first_name: Michael W.
    last_name: Coughlin
    affiliation: >
      School of Physics and Astronomy, University of Minnesota,
      Minneapolis, Minnesota 55455, USA
    orcid: 0000-0002-8262-2924
  - first_name: Peter
    last_name: Bachant
    affiliation: California Institute of Technology, Pasadena, CA 
      91125, USA
    orcid: 0000-0003-4039-6954
  - first_name: Jacob E.
    last_name: Simones
    affiliation: >
      School of Physics and Astronomy, University of Minnesota,
      Minneapolis, Minnesota 55455, USA
    orcid:
  - first_name: Thomas
    last_name: Culino
    affiliation: >
      Division of Physics, Mathematics, and Astronomy,
      California Institute of Technology, Pasadena, CA 91125, USA
    orcid: 0009-0008-3603-0013
  - first_name: Antoine
    last_name: Le Calloch
    affiliation: >
      School of Physics and Astronomy, University of Minnesota,
      Minneapolis, Minnesota 55455, USA
  - first_name: Sushant Sharma
    last_name: Chaudhary
    affiliation: >
      School of Physics and Astronomy, University of Minnesota,
      Minneapolis, Minnesota 55455, USA
    orcid: 0000-0003-1314-4241
  - first_name: Mansi
    last_name: Kasliwal
    affiliation: >
      Division of Physics, Mathematics, and Astronomy,
      California Institute of Technology, Pasadena, CA 91125, USA
    orcid: 0000-0002-5619-4938

dependencies:
  - git-lfs
  - jq

environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  analyze-logs:
    path: config/envs/analyze-logs.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13.5"
  simulate-queues:
    path: config/envs/simulate-queues.txt
    kind: uv-venv
    prefix: .venv2
    python: "3.13.5"
  run:
    path: config/envs/run.txt
    kind: uv-venv
    prefix: .venv3
    python: "3.13.5"

pipeline:
  stages:
    # TODO: Add manual step stage for exporting workflow diagram
    # TODO: Cache producer and NED loading
    benchmark-boom:
      kind: python-script
      script_path: scripts/benchmark-boom.py
      args:
        - --n-alert-workers={n_alert_workers}
        - --n-ml-workers={n_ml_workers}
        - --n-filter-workers={n_filter_workers}
      environment: run
      inputs:
        - boom/src
        - boom/Cargo.lock
        - boom/Cargo.toml
        - scripts/benchmark-boom.sh
        - config/boom/config-template.yaml
        - config/boom/compose.yaml
        - Dockerfile-boom
        - scripts/mongo-init.sh
        - data/kowalski.NED.json.gz
        - config/boom/cats150.boom.json
      iterate_over:
        - arg_name: n_alert_workers
          values: [1, 3, 6]
        - arg_name: n_ml_workers
          values: [3, 6, 9]
        - arg_name: n_filter_workers
          values: [1, 3]
        # - arg_name: repetition
        #   values:
        #     - range:
        #         start: 1
        #         stop: 50
      outputs:
        - logs/boom-na={n_alert_workers}-nml={n_ml_workers}-nf={n_filter_workers}
    benchmark-boom-more:
      kind: python-script
      script_path: scripts/benchmark-boom.py
      args:
        - --n-alert-workers={n_alert_workers}
        - --n-ml-workers={n_ml_workers}
        - --n-filter-workers={n_filter_workers}
      environment: run
      inputs:
        - boom/src
        - boom/Cargo.lock
        - boom/Cargo.toml
        - scripts/benchmark-boom.sh
        - config/boom/config-template.yaml
        - config/boom/compose.yaml
        - Dockerfile-boom
        - scripts/mongo-init.sh
        - data/kowalski.NED.json.gz
        - config/boom/cats150.boom.json
      iterate_over:
        - arg_name: [n_alert_workers, n_ml_workers, n_filter_workers]
          values:
            - [1, 1, 1]
            - [1, 2, 1]
            - [2, 2, 1]
            - [3, 4, 1]
            - [4, 6, 1]
            - [4, 7, 1]
            - [5, 8, 1]
            - [5, 5, 1]
            - [6, 10, 1]
            - [7, 11, 1]
            - [8, 13, 1]
            - [9, 15, 1]
            - [9, 14, 2]
      outputs:
        - logs/boom-na={n_alert_workers}-nml={n_ml_workers}-nf={n_filter_workers}
    benchmark-kowalski:
      kind: python-script
      script_path: scripts/benchmark-kowalski.py
      args:
        - --n-workers={n_workers}
      environment: run
      inputs:
        - config/kowalski/config-template.yaml
        - config/kowalski/compose.yaml
        - config/kowalski/supervisord.conf
        - kowalski/ingester.Dockerfile
        - kowalski/kowalski
        - kowalski/Makefile
        - kowalski/requirements
        - scripts/mongo-init.sh
        - scripts/benchmark-kowalski.sh
        - data/kowalski.NED.json.gz
        - config/kowalski/cats150.kowalski.json
      iterate_over:
        - arg_name: n_workers
          values: [3, 6, 7, 9, 12, 15, 20, 25]
      outputs:
        - logs/kowalski-n={n_workers}
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: analyze-logs
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage: git
      inputs:
        - from_stage_outputs: benchmark-boom
        - from_stage_outputs: benchmark-boom-more
        - from_stage_outputs: benchmark-kowalski
      outputs:
        - path: paper/results.tex
          storage: git
        - path: paper/figures/scaling.pdf
          storage: git
        - path: results
          storage: git
    plot-lightcurve:
      kind: python-script
      script_path: scripts/plot-lightcurve.py
      environment: analyze-logs
      inputs:
        - data/SN2025kwy.parquet
      outputs:
        - path: paper/figures/SN2025kwy.pdf
          storage: git
    build-paper:
      kind: latex
      environment: tex
      target_path: paper/main.tex
      force: true
      inputs:
        - paper/references.bib
        - paper/aasjournal.bst
        - paper/aastex631.cls
        - paper/results.tex
        - paper/diagrams
        - paper/figures

datasets:
  - path: data/kowalski.NED.json.gz
    title: NED archival catalog
    description: Alerts from the NED archival catalog exported from 
      Kowalski.
  - path: logs
    title: Benchmark logs
    description: Logs from the BOOM and Kowalski benchmarks.

figures:
  - path: paper/figures/workflow.pdf
    title: BOOM workflow
  - path: paper/figures/scaling.pdf
    title: BOOM scaling
    stage: analyze-logs
    description: This figure shows the scaling of BOOM with different 
      numbers of workers.
  - path: paper/figures/SN2025kwy.pdf
    title: Lightcurve of SN2025kwy
    stage: plot-lightcurve
    description: This figure shows the lightcurve of the supernova 
      SN2025kwy.

publications:
  - path: paper/main.pdf
    title: A real-time, multi-survey, optical alert system broker 
      operating at scale
    description:
    kind: journal-article
    stage: build-paper
    overleaf:
      project_id: 67eb247c542af4e06002e7e8
      wdir: paper
      sync_paths:
        - references.bib
        - main.tex
        - diagrams
        - results.tex
        - Orcid-ID.png
        - aasjournal.bst
        - figures
        - aastex631.cls
      push_paths:
        - results.tex
        - figures/scaling.pdf
        - figures/SN2025kwy.pdf
      last_sync_commit: 4094bff97efaba09f82d44f27dd38587fb91eaa4

notebooks:
  - path: notebooks/analyze-logs.ipynb
    title: Analyzing the logs
    description: Analyze the logs from the BOOM and Kowalski 
      benchmarks.

references:
  - path: paper/references.bib

showcase:
  - publication: paper/main.pdf

releases:
  v0.1:
    kind: project
    path: .
    git_rev: d43b20e
    date: "2025-09-29"
    publisher: caltechdata
    record_id: 640bx-nbn45
    doi: 10.22002/640bx-nbn45
    url: https://doi.org/10.22002/640bx-nbn45
    description: >
      This project contains all of the files necessary to reproduce the
      results and compile the paper.
