name: boom-paper
title: A real-time, multi-survey, optical alert system broker 
  operating at scale
environments:
  tex:
    kind: docker
    image: texlive/texlive:latest-full
    description: TeXlive via Docker.
  analyze-logs:
    path: config/envs/analyze-logs.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13.5"
  simulate-queues:
    path: config/envs/simulate-queues.txt
    kind: uv-venv
    prefix: .venv2
    python: 3.13.5
pipeline:
  stages:
    # TODO: Add manual step stage for exporting workflow diagram
    benchmark-boom:
      kind: shell-script
      script_path: scripts/benchmark-boom.sh
      environment: _system
      inputs:
        - boom/src
        - boom/Cargo.lock
        - boom/Cargo.toml
        - config/boom/config.yaml
        - config/boom/compose.yaml
        - config/boom/config-consumer.yaml
        - Dockerfile-boom
        - scripts/mongo-import-ned.sh
        - data/kowalski.NED.json.gz
      outputs:
        - logs/boom
    benchmark-kowalski:
      kind: shell-script
      script_path: scripts/benchmark-kowalski.sh
      environment: _system
      inputs:
        - config/kowalski/config.yaml
        - config/kowalski/compose.yaml
        - config/kowalski/supervisord.conf
        - kowalski/ingester.Dockerfile
        - kowalski/kowalski
        - kowalski/Makefile
        - kowalski/requirements
        - scripts/mongo-import-ned.sh
        - data/kowalski.NED.json.gz
      outputs:
        - logs/kowalski
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: analyze-logs
      html_storage: git
      executed_ipynb_storage: git
      cleaned_ipynb_storage: git
      inputs:
        - from_stage_outputs: benchmark-boom
        - from_stage_outputs: benchmark-kowalski
      outputs:
        - path: paper/results.tex
          storage: git
    build-paper:
      kind: latex
      environment: tex
      target_path: paper/main.tex
      force: true
      inputs:
        - paper/references.bib
        - paper/figures/workflow.pdf
        - paper/aasjournal.bst
        - paper/aastex631.cls
        - paper/results.tex
# These are pulled out into the run logs
metrics:
  boom_n_ml_workers:
    stage: benchmark-boom
    description: Number of BOOM machine learning workers.
    read_from:
      path: config/boom/config.yaml
      key: workers.ZTF.ml.n_workers
  boom_run_time_s:
    description: Total run time of the BOOM benchmark in seconds.
    stage: benchmark-boom
    read_from:
      path: results/results.json
      key: boom_run_time_s
  kowalski_run_time_s:
    description: Total run time of the Kowalski benchmark in seconds.
    stage: benchmark-kowalski
    read_from:
      path: results/results.json
      key: kowalski_run_time_s
datasets:
  - path: data/kowalski.NED.json.gz
    title: NED archival catalog
    description: Alerts from the NED archival catalog exported from 
      Kowalski.
figures:
  - path: paper/figures/workflow.pdf
    title: BOOM workflow
publications:
  - path: paper/main.pdf
    title: A real-time, multi-survey, optical alert system broker 
      operating at scale
    description:
    kind: journal-article
    stage: build-paper
    overleaf:
      project_id: 67eb247c542af4e06002e7e8
      wdir: paper
      sync_paths:
        - main.tex
        - references.bib
        - aasjournal.bst
        - aastex631.cls
      # Keep these out of Git in this project so we don't bloat the repo, but
      # can still version them with DVC
      dvc_sync_paths:
        - figures/workflow.key
        - figures/workflow.pdf
      push_paths:
        - results.tex
      last_sync_commit: 96ee8df1dad20ef70f8cdcf33d01c8c51de23b46
notebooks:
  - path: notebooks/analyze-logs.ipynb
    title: Analyzing the logs
    description: Analyze the logs from the BOOM and Kowalski 
      benchmarks.
references:
  - path: paper/references.bib
showcase:
  - publication: paper/main.pdf
